AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Shipment service is part of the ACME Fitness Serverless Shop. The goal of this specific service is, as the name implies, to ship products using a wide variety of shipping suppliers.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev

## Specifies the stack resources and their properties.
Resources:
  ShipmentRequestQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '${Stage}-${Feature}-shipment-request'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ShipmentErrorQueue.Arn
        maxReceiveCount: 1
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref Author
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  ShipmentResponseQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '${Stage}-${Feature}-shipment-response'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ShipmentErrorQueue.Arn
        maxReceiveCount: 1
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref Author
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  ShipmentErrorQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 120
      QueueName: !Sub '${Stage}-${Feature}-shipment-error'
      Tags: 
        - Key: version
          Value: !Ref Version
        - Key: author
          Value: !Ref Author
        - Key: team
          Value: !Ref Team
        - Key: feature
          Value: !Ref Feature
        - Key: region
          Value: !Ref AWS::Region
      VisibilityTimeout: 30
  Shipment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-sqs
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: Shipment
      Description: A Lambda function to handle shipments
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaRole
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ShipmentResponseQueue.QueueName
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          RESPONSEQUEUE: !GetAtt ShipmentResponseQueue.QueueName
      Events:
        ValidateCreditcard:
          Type: SQS
          Properties:
            Queue: !GetAtt ShipmentRequestQueue.Arn
            BatchSize: 1
            Enabled: true
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  ShipmentLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "Shipment"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Shipment]]

Outputs:
  ShipmentARN:
    Description: ARN for the Shipment function
    Value: !GetAtt Shipment.Arn
  ShipmentRequestQueueARN:
    Description: ARN for the Shipment Request Queue
    Value: !GetAtt ShipmentRequestQueue.Arn
  ShipmentResponseQueueARN:
    Description: ARN for the Shipment Response Queue
    Value: !GetAtt ShipmentResponseQueue.Arn