AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## A text string that describes the template.
Description: >
  The Shipment service is part of the ACME Fitness Serverless Shop. The goal of this specific service is, as the name implies, to ship products using a wide variety of shipping suppliers.

## Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  Version:
    Type: String
  Author:
    Type: String
  Team:
    Type: String
  Feature:
    Type: String
    Default: acmeserverless
  Stage:
    Type: String
    Default: dev
  SentryDSN:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Sentry/Dsn

## Specifies the stack resources and their properties.
Resources:
  Shipment:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-shipment-eventbridge
      Runtime: go1.x
      CodeUri: bin/
      FunctionName: !Sub "Shipment-${Stage}"
      Description: A Lambda function to handle shipments
      MemorySize: 256
      Timeout: 130
      Tracing: Active
      Policies:
        - AWSLambdaRole
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          EVENTBUS: !Ref Feature
          SENTRY_DSN: !Ref SentryDSN
          FUNCTION_NAME: Shipment
          VERSION: !Ref Version
          STAGE: !Ref Stage
      Events:
        ValidateCreditcard:
          Type: CloudWatchEvent
          Properties:
            EventBusName: !Ref Feature
            InputPath: $.detail
            Pattern:
              detail:
                metadata:
                  type:
                    - "ShipmentRequested"
      Tags:
        version: !Ref Version
        author: !Ref Author
        team: !Ref Team
        feature: !Ref Feature
        region: !Ref AWS::Region
      VersionDescription: !Ref Version
  ShipmentLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "Shipment"
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref Shipment]]

Outputs:
  ShipmentsARN:
    Description: ARN for the Shipment function
    Value: !GetAtt Shipment.Arn